language: php

sudo: required
dist: trusty

#branches:
#  only:
#    - master

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - COVERAGE=false
  matrix:
    - MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php    

matrix:
  exclude:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql IGNORE_PATHS=integration,filtersettings.php
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli IGNORE_PATHS=integration,filtersettings.php


before_install:
  - nvm install 14.0.0
  - nvm use 14.0.0
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin --branch $TRAVIS_BRANCH wiris/moodle-filter_wiris
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  # - moodle-plugin-ci grunt
  - moodle-plugin-ci behat --profile chrome